import { MiniAppManifest } from './types';

// ─────────────────────────────────────────────────────────────────────────────
// Official ablute_ Mini-App Catalog
// Manually curated — no arbitrary code loading.
//
// HOW TO ADD A NEW MINI-APP:
//  1. Deploy the web app to a HTTPS URL
//  2. Add a manifest entry below
//  3. Declare all permissions the app will use
//  4. Set featured: true if it appears in the banner
// ─────────────────────────────────────────────────────────────────────────────
export const MINI_APP_CATALOG: MiniAppManifest[] = [
  {
    id: 'introspect',
    name: '_introspect',
    tagline: 'Conversação com IA para clareza mental',
    developer: 'ablute_ Labs',
    developerVerified: true,
    category: 'mental',
    iconEmoji: '🧠',
    iconName: 'Brain',
    iconColor: '#8B5CF6',
    iconBg: 'rgba(139, 92, 246, 0.12)',
    accentColor: '#8B5CF6',
    url: 'https://introspect-ai.vercel.app/',
    permissions: ['PROFILE_READ', 'NOTIFICATIONS'],
    version: '1.0.0',
    featured: true,
    rating: 4.9,
    reviewCount: 42,
    description: 'Uma app interactiva que, através de conversação com IA, ajuda a identificar factores mentais que pesam no dia-a-dia e transforma essa leitura em acções práticas de melhoria.',
    publisher: 'ablute_ official',
    screenshots: [],
    releaseDate: '2024-04-20',
    availabilityStatus: 'available',
    consumedDomains: ['mental'],
    bridgeContractVersion: '1.4',
  },
  {
    id: 'meal-planner',
    name: '_Meal Planner',
    tagline: 'Planeamento familiar e nutrição inteligente',
    developer: 'ablute_ Labs',
    developerVerified: true,
    category: 'nutrition',
    iconEmoji: '🥗',
    iconName: 'Utensils',
    iconColor: '#10B981',
    iconBg: 'rgba(16, 185, 129, 0.12)',
    accentColor: '#10B981',
    url: 'https://eat-psi-three.vercel.app/',
    permissions: ['PROFILE_READ', 'NUTRITION_DATA_READ', 'NOTIFICATIONS'],
    version: '1.1.0',
    featured: true,
    rating: 4.8,
    reviewCount: 31,
    description: 'Planeie refeições em família de acordo com requisitos nutricionais reais, restrições e participantes por refeição, ajustando quantidades e preferências. Automatize a lista de compras e encomende diretamente para casa.',
    publisher: 'ablute_ official',
    screenshots: [
      require('../../assets/meal_planner/plano.png'),
      require('../../assets/meal_planner/receitas.png'),
      require('../../assets/meal_planner/ingredientes.png'),
      require('../../assets/meal_planner/agregado.png')
    ],
    releaseDate: '2024-04-15',
    availabilityStatus: 'available',
    consumedDomains: ['nutrition'],
    bridgeContractVersion: '1.4',
  },
  {
    id: 'deep-sleep',
    name: '_deep sleep',
    tagline: 'Monitorização e optimização do descanso',
    developer: 'ablute_ Labs',
    developerVerified: true,
    category: 'sleep',
    iconEmoji: '💤',
    iconName: 'Moon',
    iconColor: '#3B82F6',
    iconBg: 'rgba(59, 130, 246, 0.12)',
    accentColor: '#3B82F6',
    url: 'https://deepsleep-kappa.vercel.app/',
    permissions: ['PROFILE_READ', 'SLEEP_DATA_READ'],
    version: '0.9.0',
    featured: false,
    rating: 4.7,
    reviewCount: 15,
    description: 'Monitorização do sono com identificação de fases e padrões, orientada para acções práticas que ajudam a optimizar descanso, recuperação e rotina nocturna.',
    publisher: 'ablute_ official',
    screenshots: [
      require('../../assets/deep_sleep/screen1.png'),
      require('../../assets/deep_sleep/screen2.png')
    ],
    availabilityStatus: 'available',
  },
  {
    id: 'motion',
    name: '_motion',
    tagline: 'Actividade física, equilíbrio e performance',
    developer: 'ablute_ Labs',
    developerVerified: true,
    category: 'fitness',
    iconEmoji: '🏃',
    iconName: 'Activity',
    iconColor: '#10B981',
    iconBg: 'rgba(16, 185, 129, 0.12)',
    accentColor: '#10B981',
    url: 'https://motion-smoky-eta.vercel.app/',
    permissions: ['PROFILE_READ', 'ACTIVITY_DATA_READ'],
    version: '0.8.5',
    featured: false,
    rating: 4.6,
    reviewCount: 20,
    description: 'App de actividade física com vários modos de interacção, desde equilíbrio e mobilidade até desporto de alta performance, permitindo monitorização personalizada e acompanhamento próximo.',
    publisher: 'ablute_ official',
    screenshots: [],
    availabilityStatus: 'available',
  },
  {
    id: 'teleconsulta',
    name: '_TeleConsulta',
    tagline: 'Acesso rápido a aconselhamento clínico',
    developer: 'ablute_ Labs',
    developerVerified: true,
    category: 'medical',
    iconEmoji: '🩺',
    iconName: 'Heart',
    iconColor: '#EF4444',
    iconBg: 'rgba(239, 68, 68, 0.12)',
    accentColor: '#EF4444',
    url: '',
    permissions: ['PROFILE_READ'],
    version: '1.0.0',
    featured: false,
    rating: 0,
    reviewCount: 0,
    description: 'Marcação rápida e triagem inicial com profissionais de saúde para clarificar dúvidas clínicas ou obter encaminhamento imediato.',
    publisher: 'ablute_ official',
    screenshots: [],
    availabilityStatus: 'coming_soon',
  },
  {
    id: 'fem-sanctuary',
    name: '_Fem Sanctuary',
    tagline: 'Ciclos, hormonas e bem-estar feminino',
    developer: 'ablute_ Labs',
    developerVerified: true,
    category: 'female-health',
    iconEmoji: '🌸',
    iconName: 'Droplets',
    iconColor: '#EC4899',
    iconBg: 'rgba(236, 72, 153, 0.12)',
    accentColor: '#EC4899',
    url: '',
    permissions: ['PROFILE_READ'],
    version: '1.0.0',
    featured: false,
    rating: 0,
    reviewCount: 0,
    description: 'Um espaço seguro e fundamentado na ciência para acompanhar, compreender e otimizar as diferentes fases do ciclo e bem-estar geral da mulher.',
    publisher: 'ablute_ official',
    screenshots: [],
    availabilityStatus: 'coming_soon',
  },
  {
    id: 'guys-matters',
    name: '_Guy\'s matters',
    tagline: 'Performance, energia e saúde do homem',
    developer: 'ablute_ Labs',
    developerVerified: true,
    category: 'mens-health',
    iconEmoji: '💪',
    iconName: 'Zap',
    iconColor: '#3B82F6',
    iconBg: 'rgba(59, 130, 246, 0.12)',
    accentColor: '#3B82F6',
    url: '',
    permissions: ['PROFILE_READ'],
    version: '1.0.0',
    featured: false,
    rating: 0,
    reviewCount: 0,
    description: 'Monitorização focada em testosterona, recuperação, metabolismo e pilares da saúde preventiva e performance masculina.',
    publisher: 'ablute_ official',
    screenshots: [],
    availabilityStatus: 'coming_soon',
  },
  {
    id: 'brains-gym',
    name: '_Brain\'s Gym',
    tagline: 'Foco, neuroplasticidade e clareza',
    developer: 'ablute_ Labs',
    developerVerified: true,
    category: 'mental',
    iconEmoji: '🧩',
    iconName: 'Brain',
    iconColor: '#8B5CF6',
    iconBg: 'rgba(139, 92, 246, 0.12)',
    accentColor: '#8B5CF6',
    url: '',
    permissions: ['PROFILE_READ'],
    version: '1.0.0',
    featured: false,
    rating: 0,
    reviewCount: 0,
    description: 'Exercícios cognitivos, protocolos de foco e ferramentas de descompressão mental projetadas para otimizar o desempenho do cérebro no dia a dia.',
    publisher: 'ablute_ official',
    screenshots: [],
    availabilityStatus: 'coming_soon',
  },
  {
    id: 'longevity-studio',
    name: '_Longevity Studio',
    tagline: 'Saúde preventiva e biomarcadores de envelhecimento',
    developer: 'ablute_ Labs',
    developerVerified: true,
    category: 'longevity',
    iconEmoji: '⏳',
    iconName: 'Target',
    iconColor: '#14B8A6',
    iconBg: 'rgba(20, 184, 166, 0.12)',
    accentColor: '#14B8A6',
    url: '',
    permissions: ['PROFILE_READ'],
    version: '1.0.0',
    featured: false,
    rating: 0,
    reviewCount: 0,
    description: 'Planeamento a longo prazo baseado na tua saúde celular e metabólica. Foca-te em anos de vida com qualidade através de intervenções científicas e rastreio.',
    publisher: 'ablute_ official',
    screenshots: [],
    availabilityStatus: 'coming_soon',
  },
];

export const getFeaturedApp = (): MiniAppManifest | undefined =>
  MINI_APP_CATALOG.find((app) => app.featured);

export const CATEGORY_LABELS: Record<string, string> = {
  'female-health': 'Saúde Feminina',
  'mens-health': 'Saúde Masculina',
  'medical': 'Saúde e Clínica',
  'sleep': 'Sono',
  'nutrition': 'Nutrição Personalizada',
  'mental': 'Autoconhecimento',
  'fitness': 'Movimento',
  'longevity': 'Longevidade',
};
